modLoader = "javafml"
loaderVersion = "[45,)"
issueTrackerURL = "https://github.com/AviatorRob/disx"
license = "Apache 2.0"

[[mods]]
modId = "disx"
version = "${version}"
displayName = "Disx"
authors = "Aviator_Rob"
description = '''
Burn YouTube videos' audio onto discs, and play them back in real time!
'''
logoFile = "icon.png"
state="ALPHA"

[[dependencies.disx]]
modId = "forge"
mandatory = true
versionRange = "[47.2.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disx]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.disx]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"